school_database/school_database/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('website.urls'))
]

school_database/website/urls.py
from django.urls import path
from.views import home, register, log_in, admin, student, staff, editor, log_out


app_name = 'website'

urlpatterns = [
    path('', home, name='home'),
    path('register/', register, name='register'),
    path('log-in/', log_in, name='log_in'),
    path('admin-page/', admin, name='admin'),
    path('student-page/', student, name='student'),
    path('staff-page/', staff, name='staff'),
    path('editor-page/', editor, name='editor'),
    path('log-out/', log_out, name='log_out'),
]

school_database/website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(max_length=60, unique=True)
    country = models.CharField('Country', max_length=150, blank=True)
    nationality = models.CharField('Nationality', max_length=150, blank=True)
    mobile = models.PositiveBigIntegerField('Mobile', null=True, blank=True)
    admin = models.BooleanField('Admin', default=False)
    student = models.BooleanField('Student', default=False)
    staff = models.BooleanField('Staff', default=True)
    editor = models.BooleanField('Editor', default=False)

school_database/website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class LoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
   
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    country = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    nationality = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    mobile = forms.IntegerField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'country', 'nationality', 'mobile', 'admin', 'student', 'staff','editor')

school_database/website/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

from .models import User
from .forms import RegisterForm, LoginForm
from .decorators import admin_only, student_only, staff_only, editor_only


def home(request):
    return render(request, 'index.html')


def register(request):
    form = RegisterForm()
    counter = 0
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            counter += form.cleaned_data.get('admin')
            counter += form.cleaned_data.get('student')
            counter += form.cleaned_data.get('staff')
            counter += form.cleaned_data.get('editor')
            if counter == 0:
                messages.error(request, "You must choose a role!")
                return redirect('website:register')
            elif counter > 1:
                messages.error(request, "You can choose only one role!")
                return redirect('website:register')
            else:
                form.save()
                messages.success(
                    request, "Your account has been successfully created.")
                return redirect('website:log_in')

    return render(request, 'register.html', {'form': form})


def log_in(request):
    form = LoginForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = User.objects.get(email=email)
            print(email)
            print(password)

            if user.check_password(password):
                if user.admin:
                    login(request, user)
                    return redirect("website:admin")
                elif user.student:
                    login(request, user)
                    return redirect("website:student")
                if user.staff:
                    login(request, user)
                    return redirect("website:staff")
                if user.editor:
                    login(request, user)
                    return redirect("website:editor")

        else:
            messages.error(request, "Bad Credentials!")
            return redirect('website:log_in')

    return render(request, 'login.html', {'form': form})


@login_required(login_url='website:log_in')
@admin_only
def admin(request):
    return render(request, 'admin.html')


@login_required(login_url='website:log_in')
@student_only
def student(request):
    return render(request, 'student.html')


@login_required(login_url='website:log_in')
@staff_only
def staff(request):
    return render(request, 'staff.html')


@login_required(login_url='website:log_in')
@editor_only
def editor(request):
    return render(request, 'editor.html')


def log_out(request):
    logout(request)
    return redirect('website:home')

school_database/templates/admin.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Admin {% endblock %}


{% block body %}

<h1>Welcome <span class="username">{{ user.username }}</span></h1>

{% endblock %}

school_database/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href=" {% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href=" {% static 'css/styles.css' %}" rel="stylesheet">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    
{% include 'header.html' %}

{% block body %}
{% endblock %}


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

school_database/templates/editor.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Editor {% endblock %}


{% block body %}

<h1>Welcome <span class="username">{{ user.username }}</span></h1>

{% endblock %}

school_database/templates/header.html
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
    <div class="container-fluid">
        {% if user.admin %}
        <a class="navbar-brand" href="{% url 'website:home' %}">ABC School | Admin Page</a>
        {% elif user.student %}
        <a class="navbar-brand" href="{% url 'website:home' %}">ABC School | Student Page</a>
        {% elif user.staff %}
        <a class="navbar-brand" href="{% url 'website:home' %}">ABC School | Staff Page</a>
        {% elif user.editor %}
        <a class="navbar-brand" href="{% url 'website:home' %}">ABC School | Editor Page</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'website:home' %}">ABC School</a>
        {% endif %}
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'website:home' %}">Home</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'website:log_out' %}">LogOut</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'website:log_in' %}">LogIn</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                        href="{% url 'website:register' %}">Register</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

school_database/templates/index.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} ABC School {% endblock %}


{% block body %}

<div class="container-fluid home-card">

    <div class="row">

        <div class="shadow col-md-12">
            <div class="card-body">
                <h1>WELCOME</h1>
                {% if user.is_authenticated %}
                <div>
                    {% for message in messages %}
                    <div class="messages">
                        <h4 style="color: red; font-size: 1.5rem;">{{ message }}</h4>
                    </div>
                    {% endfor %}
                    <div>
                        {% if user.admin %}
                        <a href="{% url 'website:admin' %}">Return to Admin Page</a>
                        {% elif user.student %}
                        <a href="{% url 'website:student' %}">Return to Student Page</a>
                        {% elif user.staff %}
                        <a href="{% url 'website:staff' %}">Return to Staff Page</a>
                        {% elif user.editor %}
                        <a href="{% url 'website:editor' %}">Return to Editor Page</a>
                        {% endif %}
                    </div>
                </div>
                {% else %}
                <div>
                    <a href="{% url 'website:register' %}" class="btn btn-outline-primary">Register</a>
                    <a href="{% url 'website:log_in' %}" class="btn btn-outline-success">LogIn</a>
                </div>
                {% endif %}
            </div>
        </div>

    </div>

</div>

{% endblock %}

school_database/templates/login.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Login {% endblock %}


{% block body %}

<div class="login-form">

    <form action="" method="POST">
        <h2>LOG IN</h2>

        {% for message in messages %}
        <div class="messages" style="font-size: 1.5rem;">
            {{ message }}
        </div>
        {% endfor %}

        {% csrf_token %}

        {{ form }}

        <br>
        <div class="d-grid">
            <button class="btn btn-primary" type="submit">SignIn</button>
        </div>
    </form>

</div>

{% endblock %}

school_database/templates/register.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Register {% endblock %}


{% block body %}

<div class="register-form">

    <form action="" method="POST">
        <div class="heading">
            <h2>Register</h2>
        </div>
        {% for message in messages %}
        <div class="messages">
            <h4 style="color: red; font-size: 1.5rem;">{{ message }}</h4>
        </div>
        {% endfor %}
        {% csrf_token %}

        {{ form.as_p }}
        
        <br>
        <div class="d-grid">
            <button class="btn btn-primary" type="submit">SignUp</button>
        </div>
    </form>

</div>

{% endblock %}

school_database/templates/staff.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Staff {% endblock %}


{% block body %}

<h1>Welcome <span class="username">{{ user.username }}</span></h1>

{% endblock %}

school_database/templates/student.html
{% extends 'base.html' %}

{% block metadescription %}
{% endblock %}

{% block title %} Student {% endblock %}


{% block body %}

<h1>Welcome <span class="username">{{ user.username }}</span></h1>

{% endblock %}